interface to Cryptolog platform to sign Tryton ir.attachments
coopengo/trytond-cryptolog pull request #1
Opened 2017-03-13 17:03 UTC by alikefia

2017-03-13 17:31 UTC, JCavallo requested changes

2017-03-13 17:31 UTC, JCavallo commented on __init__.py
> +from attachment import Attachment, AttachmentSigner
De nos jours, on préfère :

```
import attachment


def register():
    Pool.register(
        attachment.Attachment,
        ...
```

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +import xmlrpclib
Missing copyright header

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +from trytond.pool import PoolMeta
Style : Separate lib imports ffrom trytond imports

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +__all__ = ['Attachment', 'AttachmentSigner']
Style :

```
__all__ = [
    'Attachment',
    'AttachmentSigner',
    ]
```

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    "Attachment Signer"
Style : Single quotes

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +class AttachmentSigner(ModelSQL):
Style : les classes intermédiaires de M2M sont en général placées après le modèle principal

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    attachment = fields.Many2One('ir.attachment', 'Attachment')
required, ondelete, select

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    signer = fields.Many2One('party.party', 'Signer')
required, ondelete, select

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    __name__ = 'cryptolog.attachment-signer'
Style : on préfixe avec le nom du modèle principal

`ir.attachment.cryptolog_signatory`

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +        'attachment', 'signer', 'Cryptolog Signers')
D'après @PierreJackman et @google on dit Signatory

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +section = 'cryptolog'
A mettre en majuscule pour identifier le fait que c'est une globale :

`CONFIG_SECTION = 'cryptolog'`

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    cryptolog_url = fields.Char('Cryptolog URL', readonly=True)
Il manque des states sur ces deux champs (required à partir du moment où le status est à autre chose que ready probablement)

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +    cryptolog_data = fields.Function(fields.Binary('Signed Document',
Style : Saut de ligne avant le fields.Binary

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            filename='name',
Style : Autant que possible, tout mettre sur la même ligne

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            readonly=True,
Inutile, c'est un champ Fonction sans setter, il sera forcément readonly

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            }, depends=['cryptolog_status']), 'cryptolog_get_documents')
Style : Mettre le nom du getter sur une autre ligne

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +                'invisible': Eval('cryptolog_status') != 'completed'
Il ne faudrait pas historiser l'information si le statut est 'expired' ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            return {'Content-Type': 'application/xml'}
C'est quoi l'intérêt d'en faire une méthode ? Une surcharge est prévue ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +        attachment, = attachments
Commentaire pour expliquer qu'on ne supporte qu'un document à la fois, et pourquoi

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +        verify = False if config.get(section, 'no_verify') == '1' else True
Toute la lecture de la configuration pourrait être fait une seule fois à l'initialisation et stockée dans des variables globales non ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            }],
Style : indentation

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +                'documentType': 'pdf',
Pas forcément, si ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +                'phoneNum': p.phone
Il faudrait peut-être vérifier que les champs en question sont bien renseignés non ? Peut-être ajouter un warning ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +            raise Exception(req.content)
Pour moi il faut faire un truc plus propre, s'il y a un problème lors de la connection, ce n'est pas le problème de l'utilisateur, il faut plutôt un truc du style "Impossible de se connecter au serveur, veuillez prévenir un administrateur"

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +        attachment.save()
Je n'ai pas l'impression qu'on change le state, si ?

2017-03-13 17:31 UTC, JCavallo commented on attachment.py
> +        if Transaction().context.get('%s.%s' % (self.__name__, name)) == \
???

2017-03-13 17:31 UTC, JCavallo commented on view/attachment_form.xml
> +        <page string="Cryptolog">
Il ne faut pas mettre un id ?

2017-03-13 17:31 UTC, JCavallo commented
+ traductions et tests

2017-03-14 11:31 UTC, romainseon reviewed
Le nom du module c'est vraiment ce qu'on veut? Quand on voit https://pypi.python.org/pypi?%3Aaction=search&term=trytond&submit=search tout les modules de trytond ne sont pas forcement préfixé de trytond. De plus ce serait bien d'avoir un minimum de doc (features.rst ou équivalent) histoire d'y penser au moment de la sortie de la doc

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +    'Attachment'
Style : virgule en fin de ligne

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +           })
Missing depends

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +            return {'Content-Type': 'application/xml'}
up ?

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +        attachment, = attachments
Up

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +        password = config.get(CONFIG_SECTION, 'password')
Je ne comprend pas pourquoi ce ne sont pas des constantes en début de fichier

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +            verify = False
A mettre en début de fichier.

```
verify = config.get(CONFIG_SECTION, 'no_verify') != '1'

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +        method = 'requester.requestTransaction'
Constante en début de fichier

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +            raise Exception(req.content)
Mettre un message utilisateur et une log serveur, ça ne sert à rien d'afficher une stack à l'utillisateur

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +        if req.status_code > 299:
Ca ne serait pas != 200 ?

2017-03-15 17:16 UTC, JCavallo commented on attachment.py
> +        if Transaction().context.get('%s.%s' % (self.__name__, name)) == \
Ajouter un commentaire pour expliquer

2017-03-16 09:12 UTC, alikefia commented on attachment.py
> +        if req.status_code > 299:
Généralement les 2xx sont OK (je pense notamment que dans le cas de Cryptolog ce n'est pas un 200)

2017-03-16 09:13 UTC, alikefia commented on attachment.py
> +            raise Exception(req.content)
Sentry fait ça en général

2017-03-16 09:13 UTC, alikefia commented on attachment.py
> +        method = 'requester.requestTransaction'
C'est pareil (trytond ne lit pas dans le FS)

2017-03-16 09:23 UTC, alikefia commented on attachment.py
> +            return {'Content-Type': 'application/xml'}
pratique de factoriser, si jamais y en a d'autres à rajouter

2017-03-16 16:49 UTC, merged